### ISSUE TITLE
[CK][Support] Ticket #362 will affect the report. #194

### ISSUE THREAD

**Issue by garimadosar5** [OpenCHS/calcutta-kids#27]
Report - https://reporting.openchs.org/question/194

In this report add the column "Attended last community meetup?". instead of Meeting attendance (YES/NO).

Form Changes are done in the card 
https://app.zenhub.com/workspaces/openchs-5cf8e458bf08585333fd64ac/issues/openchs/calcutta-kids/3

Ticket: https://openchs.freshdesk.com/a/tickets/362

**Comment by sachsk** [comment]
fixed

**Comment by garimadosar5** [comment]
@sachsk 
QA Notes - 
- Other Specify Column is not added.
- Planned Visit Date - November 1, 2018
  Area - 2
  Name - Zunahra Khatoon
  MyCHI ID - G2511 
This Row does not have either data in column Cancel Reason nor in Community Attendance column. This seems like old enrolment or something.
