### ISSUE TITLE
[Bug][Report]Sync Report - Numbers dont seem to match actual data

### ISSUE THREAD

**Issue by nubrapika** [OpenCHS/calcutta-kids#5]
The report is showing a lot more enrolments and individuals than its actually done every month.
Check encounters also.

**Comment by garimadosar5** [comment]
@nubrapika  Please put the report links where the numbers are a mismatch and also add the ticket number (if there is a ticket).

**Comment by vindeolal** [comment]
This report doesn't give total registration, enrollment or encounter number. The report gives the number of entities synced within a selected date range. So even if the enrollment happened last month but it  was edited this month and synced it will still get counted in the report.

**Comment by arjunk** [comment]
@garimadosar5 @nubrapika Based on @vindeolal 's analysis and previous comment on this card, we now need to further input from you if there is anything we need to do on this or just move to complete.

**Comment by nubrapika** [comment]
@Arjun Khandelwal <arjunk@samanvayfoundation.org>

This report was not explicitly requested by CK. We created it. I dont think
the current logic fits their requirement. I dont think they are willing to
pay extra to make this work. Let's remove it.
