### ISSUE TITLE
[CK] Cancel Visit form for Doctor Visit Followup at Home

### ISSUE THREAD

**Issue by nubrapika** [OpenCHS/calcutta-kids#7]
Form options are 

i) Patient is improved - रोगी में सुधार हुआ है 
ii) Visited other Doctor  - दुसरे डॉक्टर को व्हिसिट किया है 
iii) Away from Fakir Bagan - फकीर बागान से बाहर गये है 
iv) Not interest to followup - फालोअप के लिये नहीं आना चाहते हैं 
v) Other, Specify Other ________________ - अन्य , अन्य स्पष्ट करें _______________

- After cancel NOTHING will happen. No new visit schedule.

Need translation as well. 

https://openchs.freshdesk.com/a/tickets/406

**Comment by nubrapika** [comment]
@garimadosar5 please add the scheduling logic that will be triggered on cancellation of this visit.

**Comment by arjunk** [comment]
@garimadosar5 @nubrapika APK (with translations) Available at https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-28bc4-2019-09-13-15-12-52.apk moving the story to QA ready.
